title: "Vijay's Blog"
description: "My personal tech and cyber blog"
url: "https://singhvijayp.github.io"
baseurl: "/blog"

remote_theme: "mmistakes/minimal-mistakes"
skin: "contrast"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
