title: Vijay's Blog
baseurl: "/blog" # important for hosting in folder
url: "https://singhvijayp.github.io" # replace with your GitHub username

remote_theme: "mmistakes/minimal-mistakes@4.27.1"

skin: "contrast"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude: ["node_modules", "vendor", "Gemfile", "Gemfile.lock"]

markdown: kramdown
