title: "Vijay's Blog"
description: "A tech & cybersecurity blog"
url: "https://singhvijayp.github.io"
baseurl: "/blog"

remote_theme: "mmistakes/minimal-mistakes"
skin: "contrast"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

markdown: kramdown

exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor"]
